---
apiVersion: gpte.redhat.com/v1
kind: ResourceClaim
metadata:
  generateName: resource-claim-
spec:
  template:
    apiVersion: gpte.redhat.com/v1
    kind: AnarchySubject
    metadata:
      labels:
        governor: test
    spec:
      desiredState: deployed
      governor: test
      parameters:
        test_str: bar
        test_int: 23
        test_float: 23.3
